version: '3'
services:
  cache:
    ports:
      - "8888:80"
  database:
    image: mariadb:10.2
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
volumes:
  db-data:
